### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by mcgregorian1** [seanmcm/RDendrom#2]
Hi @seanmcm 

I've tried the code again (prepping for a thing with high schoolers showing how the dendroband data can be analyzed), and I found the following error when running `get.optimized.dendro`.  I'm not sure what's gone wrong here.

![image](https://user-images.githubusercontent.com/39522449/59275447-555a3100-8c2a-11e9-9b03-fd7b14a2737d.png)

[Here](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/results/tree_10045.csv) is the dataset I was using.

**Comment by seanmcm** [comment]
@mcgregorian1 did you fix this? I get this usually when there is a missing value in ORG_DBH[1] or an NA in GAP_WIDTH (anywhere). So i do complete.cases(dataf$GAP_WIDTH) before beginning. 

couldn't get the data if you're still having trouble. Please reload the package as well, as I've changed some things (minor, but bugs also).

**Comment by mcgregorian1** [comment]
I've double-checked the df and there are no missing elements, but I'm getting the same error message.

I think you have access to our Dendroband repo? https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/results/tree_10045.csv

If not let me know and I can send the file via email

**Comment by seanmcm** [comment]
@mcgregorian1 
Looks like there is no $ORG_DBH, that is, the original dbh which is needed to translate the gap width into a starting DBH, and then build "TRUE_DBH" from the changes in the increment in the gap.

**Comment by mcgregorian1** [comment]
@seanmcm in the file I linked there is an ORG_DBH, which is column 22.

**Comment by seanmcm** [comment]
@mcgregorian1  I fixed some code that created that error. But it had to do with extra bands. this afternoon I'll check the data you linked to. sorry I didn't see to scroll right to find many more columns!

**Comment by mcgregorian1** [comment]
That's fine! Let me know when you'd like me to try again on my end

**Comment by mcgregorian1** [comment]
Hi @seanmcm 

I tried your code again, and it's worked. However, I've gotten an error further down that I'm unsure about what it means? The graphs were still made, though, so I'm not sure of its importance.

![image](https://user-images.githubusercontent.com/39522449/59706984-adb3a480-91cf-11e9-91c7-c4e835bef172.png)
![image](https://user-images.githubusercontent.com/39522449/59706999-b73d0c80-91cf-11e9-8402-ab91ddf0a700.png)
![image](https://user-images.githubusercontent.com/39522449/59707026-c15f0b00-91cf-11e9-908b-c8dc1625e296.png)


The other thing is that in `Dendro.split` I'm getting NULL values; it seems these are made because of incomplete growing seasons? e.g. `Dendro.split[[1]]` is supposed to be data from 2010, but that only has one data point. `Dendro.split[[10]]` is the data from 2019, for which we have half a year's data so far. I'm assuming the fact that it's NULL is because your code is recognizing it as not complete?
![image](https://user-images.githubusercontent.com/39522449/59707301-5d891200-91d0-11e9-9c16-e4701f1a5076.png)

**Comment by seanmcm** [comment]
Got it.  This likely disrupted other output. Data-set is a variable we use to designate different projects.  I’ll fix that this evening so you can run it again. Thanks.

**Comment by seanmcm** [comment]
@mcgregorian1 
OK, fixed the DATA_SET problem. you should re-run.
For NULL values, I set a minimum observations in the time series to 9. this is an argument in the get.optimized.dendro function and so can be changed. The NULL is kept in so that it still maps to the param.table output data.frame with summary results for each time series. This way, the number of rows in the data.frame should be the same as the number of elements in the Dendro.split output. The data.frame will have NAs for fit parameters, but still retain details about what was not fit (year, species, tree_id, etc.). do you think I should change this?

**Comment by mcgregorian1** [comment]
Hm, that's a good question. I think it depends on what your original reason for limiting the minimum to 9 observations was. What's the min number you need to create the growth curve? I don't have a sound scientific reason off the top of my head that it should be lower, except for that perhaps someone would want to see how the growth trajectory of a tree in the current year is going, even though that year isn't done yet.
- so, for example, if this year I noticed something off with one tree, and I wanted to graph it to see if it's in line with previous years' growth. Currently with the code, I can't do that because I have <9 observations so far.

## Other error
I downloaded your edits from Github and I'm now receiving this when using the code `devtools::install_github("seanmcm/RDendrom")`
![image](https://user-images.githubusercontent.com/39522449/59782547-27a96380-928c-11e9-8aab-04ad17890fff.png)

**Comment by seanmcm** [comment]
@mcgregorian1 OK Should work now. had to clean and re-build after removing a redundant function.

**Comment by mcgregorian1** [comment]
@seanmcm I just tested it and the main functions ran well. Looks good!
