### ISSUE TITLE
Error get.optimized.dendro

### ISSUE THREAD

**Issue by jess-shue** [seanmcm/RDendrom#6]
The TEMPEST data did not include 'Skip', 'Adjust', and 'Remove' columns, so I've added those and set them all = 0. Now, get.optimized.dendro is giving this error:
`Error in optimize(.difdendro, interval = c(0, dbh1 + 2 * gw2), gw2 = gw2,  : 
  invalid 'xmin' value`

I've looked into the DENDRO_BASE_FUNCTIONS for .difdendro, but I'm not sure how to fix the problem.

**Comment by seanmcm** [comment]
look for a minimum evaluator min(). it’s getting something it can’t evaluate. an na or nan. i’ll look at this tomorrow.
